name: Deploy master
on:
  push:
    branches:
      - master
  watch:
    types: [started]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Generate deployment package
      run: zip deploy.zip src/*/** package.json yarn.lock Dockerfile
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ListasujacoronaApi-api
        environment_name: ListasujacoronaApi-prod
        region: us-east-1
        deployment_package: deploy.zip
        use_existing_version_if_available: true
        version_label: 12345
